version: 3

groups:
  secretaries:
    reviews:
      request: 10
      required: 1
    reviewers:
      teams:
      - secretaries
    conditions:
    - "'proposed/*' not in files or 'proposed/psr-8*' in files or 'Internal: Bylaw or Admin Change' in labels or 'New PSR' in labels"
  security:
    reviews:
      request: 1
      required: 1
      request_order: given
    reviewers:
      users:
      - michaelcullum
      teams:
      - psr-9-10
    conditions:
    - "'proposed/security*' in files"
  phpdoc:
    reviews:
      request: 0
      required: 1
    reviewers:
      teams:
      - psr-5
    conditions:
    - "'proposed/phpdoc*' in files"
  cs-extended:
    reviews:
      request: 10
      required: 1
    reviewers:
      teams:
      - psr-12
    conditions:
    - "'proposed/extended-coding-style-guide*' in files"
  event-dispatcher:
    reviews:
      request: 10
      required: 1
    reviewers:
      teams:
      - psr-14
    conditions:
    - "'proposed/event-dispatcher*' in files"
